### ISSUE TITLE
[Leave Request screen] Upload one attachment >10 MB display error message but Submit successfully

### ISSUE THREAD

**Issue by at-loannguyen** [queenscity/internship-2019-summer#2]
**Test Environment**
- Date time: 08/07/2019 11:35
- Web: Window 10, Google Chrome, Version 10.0.17763

**Pre-Condition**
- [Leave Request] screen is opened

**Steps to perform**
1. Select one attachment >10 MB 
2. Input valid data into remain fields 
3. Click [Submit] button

**Actual Result**
- At step 1: Display error message: " name file: Invalid file size, maximum upload size is 10MB"
- At step 3: Submit successfully

**Expected Result**
- Suggestion: At step 3: 
Option 1: Display an error message and submit unsuccessfully
Option 2: Display an Notice for user that save success but without attachment and submit successfully 

--> In my opinion, I think we should use option 2 with a friendly notice. 

**Video**
https://drive.google.com/open?id=1y-SRtkr-_KioNZ9uKEg97zf6SVIhktc5

**Comment by at-quynhnguyen** [comment]
@at-loannguyen 
The content of this issue is OK. 
And I raised for AT-Portal project about this issue. 
Thank you!
