### ISSUE TITLE
[Leave Request screen] The first file was chosen (<10Mb) is disappear when adding the second file had greater capacity 10Mb

### ISSUE THREAD

**Issue by at-loannguyen** [queenscity/internship-2019-summer#3]
**Test Environment**
- Date time: 08/07/2019 3:00 PM
- Web: Window 10, Google Chrome, Version 10.0.17763

**Pre-Condition**
- [Leave Request] screen is opened

**Steps to perform**
1. Select one attachment <10 MB 
2. Select one attachment >10 MB 
3. Check file attachment 

**Actual Result**
- At step 3: The first file was chosen (<10Mb) is disappear when adding the second file had greater capacity 10Mb

**Expected Result**
- At step 3: 
  + The first file was chosen (<10Mb) is displayed correctly when adding the second file had greater capacity 10Mb 
  + Display error message below file was chosen previously

**Video**
https://drive.google.com/open?id=1aYvyHPdhG34gjyeG7v2zvd31dHnDE3zE

**Comment by at-quynhnguyen** [comment]
@at-loannguyen 
The content of this issue is OK. 
And I raised for AT-Portal project about this issue. 
Thank you!
